### ISSUE TITLE
Build instruction issue

### ISSUE THREAD

**Issue by andr229k** [ajxs/yamaha_dx97#1]
This project is great, but the build instructions to generate a binary seems not rhetorical knowledge for all potential testers, who would be able to get the firmware installed and report their end-user feedback/experience to support/contribute to this project.

Would it be possible to generate a folder with the binary pre-made [and then update it from time-to-time] or alternatively elaborate on "how to run make"?

**Comment by ajxs** [comment]
Hello,
Thank you so much for your interest in the project! I really appreciate you taking the time to raise this issue. This is a good point. When I first released this project to the public, I was worried about wasting people's time if they went to the trouble of installing the new ROM, only to encounter some nasty bug. I figured I'd wait until a v1.0 release before I released pre-made binaries for this reason. 
As of this week, I'm actually in the process of working through a long checklist of tests before I release the v1.0 version, so this has come up at the right time. If you can wait a few days, I can expedite my testing and try to get this sorted for you. How about I update this issue once I finish testing and publish the pre-built v1.0 binary?
P.S: Since making the project public I have actually fixed a few serious bugs, which is a bit embarrassing. That's just writing software I guess!

**Comment by ajxs** [comment]
With regards to `make`, and building the ROM. This week I'll write up some better instructions about setting up a development environment for users who want to build the binary, and put those in the `README`.

**Comment by andr229k** [comment]
Thank you for the feeback [ajxs](https://github.com/ajxs) ,

I’m looking forward for the 1.0 release and thank you for making this possible for the Yamaha DX9/7 users.

**Comment by andr229k** [comment]
> With regards to `make`, and building the ROM. This week I'll write up some better instructions about setting up a development environment for users who want to build the binary, and put those in the `README`.

Any updates? ;)

**Comment by ajxs** [comment]
Thank you for your patience! I've just made a public beta release of the firmware binary on this Github page. You should be able to download it now. I've given the firmware some basic testing, and things look good. There's some minor things I want to investigate further, but for the most part the major functionality is all in place. I'll continue my testing this week, and if all goes well I'll move towards a v1.0 release.
If you have any issues with the download, please let me know!

**Comment by andr229k** [comment]
> e of the firmware binary on this Github page. It's available [here](https://github.com/ajxs/yamaha_dx97/releases/tag/v0.9.5). I've given the firmware some basic testing, and things look good. There's some minor things I want to investig

Any updates concerning the release of 1.0 or maybe a new build with the latest changes? ;)

**Comment by ajxs** [comment]
Thank you for your continued interest! And thank you for reminding me to publish a new release with the latest changes too. I've done that now.
I've actually been doing a lot of work on this recently! There are a few bugs in reading patches over the cassette interface that I need to iron out. I anticipate having this done in 2 weeks or so. I know the cassette interface isn't the most important feature in 2023, however I don't want to remove it when there's a chance to have it all working.
I haven't forgotten about improving the build documentation either! When I publish the next round of changes I'll be updating that.

**Comment by ajxs** [comment]
I've managed to resolve all of the known issues. If there aren't any new issues found after a few weeks, the current version will become the initial v1.0.0 release. I'll close this issue now. Thanks for all your help!
